POST http://localhost:8091/api/votes
Content-Type: application/json

{
  "comment": "http://localhost:8091/api/comments/4",
  "user": "http://localhost:8091/api/users/admin"
}

###

POST http://localhost:8091/api/votes
Content-Type: application/json

{
  "post": "http://localhost:8091/api/posts/1",
  "user": "http://localhost:8091/api/users/admin"
}
