logging:
  level:
    org:
      springframework:
        security: debug
spring:
  datasource:
    url: jdbc:h2:mem:homework-db
  #    url: jdbc:h2:file:~/homework-db
  data:
    rest:
      base-path: /
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 80