logging:
  level:
    org:
      springframework:
        security: info
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    #    url: jdbc:h2:mem:homework-db
    url: jdbc:h2:file:~/homework-db
  data:
    rest:
      base-path: /api
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8091
